[versions]
androidx-appcompat = "1.6.1"
androidx-biometric = "1.1.0"
androidx-constraintlayout = "2.1.4"
androidx-core-ktx = "1.10.1"
androidx-datastore-preferences = "1.0.0"
androidx-fragment-ktx = "1.5.7"
androidx-lifecycle = "2.6.1"
androidx-preference-ktx = "1.2.0"
androidx-room = "2.5.1"
androidx-test-espresso = "3.5.1"
androidx-test-ext-junit-ktx = "1.1.5"
androidx-test-orchestrator = "1.4.2"
androidx-test-uiautomator = "2.3.0-alpha03"
app-cash-turbine = "0.13.0"
com-android-application = "8.0.1"
com-github-ben-manes-versions = "0.46.0"
com-github-chrisbanes-photoview = "2.3.0"
com-github-jk1-dependency-license-report = "2.1"
com-github-lisawray-groupie = "2.10.1"
com-google-android-material = "1.9.0"
com-google-devtools-ksp = "1.8.21-1.0.11"
com-google-zxing-core = "3.3.3"
com-tom-roush-pdfbox-android = "2.0.25.0"
io-gitlab-arturbosch-detekt = "1.22.0"
io-kotest-assertions-core = "5.6.2"
io-mockk = "1.13.5"
kotlin = "1.8.21"
nl-littlerobots-version-catalog-update = "0.8.0"
org-jetbrains-kotlinx-coroutines-test = "1.7.1"
org-robolectric = "4.10.2"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "androidx-biometric" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore-preferences" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment-ktx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "androidx-preference-ktx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-test-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "androidx-test-espresso" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-ext-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-ext-junit-ktx" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidx-test-orchestrator" }
androidx-test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "androidx-test-uiautomator" }
app-cash-turbine = { module = "app.cash.turbine:turbine", version.ref = "app-cash-turbine" }
com-github-chrisbanes-photoview = { module = "com.github.chrisbanes:PhotoView", version.ref = "com-github-chrisbanes-photoview" }
com-github-lisawray-groupie = { module = "com.github.lisawray.groupie:groupie", version.ref = "com-github-lisawray-groupie" }
com-github-lisawray-groupie-viewbinding = { module = "com.github.lisawray.groupie:groupie-viewbinding", version.ref = "com-github-lisawray-groupie" }
com-google-android-material = { module = "com.google.android.material:material", version.ref = "com-google-android-material" }
com-google-zxing-core = { module = "com.google.zxing:core", version.ref = "com-google-zxing-core" }
com-tom-roush-pdfbox-android = { module = "com.tom-roush:pdfbox-android", version.ref = "com-tom-roush-pdfbox-android" }
io-kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "io-kotest-assertions-core" }
io-mockk = { module = "io.mockk:mockk", version.ref = "io-mockk" }
org-jetbrains-kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "org-jetbrains-kotlinx-coroutines-test" }
org-robolectric = { module = "org.robolectric:robolectric", version.ref = "org-robolectric" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "com-android-application" }
com-github-ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "com-github-ben-manes-versions" }
com-github-jk1-dependency-license-report = { id = "com.github.jk1.dependency-license-report", version.ref = "com-github-jk1-dependency-license-report" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "com-google-devtools-ksp" }
io-gitlab-arturbosch-detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "io-gitlab-arturbosch-detekt" }
nl-littlerobots-version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "nl-littlerobots-version-catalog-update" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
org-jetbrains-kotlin-plugin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
