opt_out_usage

lane :google do
    upload_to_play_store(
      json_key_data: ENV["PLAYSTORE_KEY"],
      aab: ENV["AAB_FILE"],
      track: "internal",
    )
end

lane :huawei do
    huawei_appgallery_connect(
        client_id: ENV["HUAWEI_CLIENT_ID"],
        client_secret: ENV["HUAWEI_CLIENT_SECRET"],
        app_id: "108212859",
        apk_path: ENV["AAB_FILE"],
        is_aab: true,
        submit_for_review: false,
    )
end

lane :amazon do
    upload_to_amazon_appstore(
      client_id: ENV["AMAZON_CLIENT_ID"],
      client_secret: ENV["AMAZON_CLIENT_SECRET"],
      apk: ENV["APK_FILE"],
      changes_not_sent_for_review: true,
    )
end
