build_dir = ENV["BUILD_DIR"]
version_code = ENV["VERSION_CODE"]

lane :google do
    upload_to_play_store(
      aab: "#{build_dir}/app-release.aab",
      json_key_data: ENV["PLAY_STORE_CREDENTIALS"],
      track: "internal",
      package_name: "com.michaeltroger.gruenerpass",
    )
end

lane :huawei do
    huawei_appgallery_connect(
        client_id: ENV["HUAWEI_CLIENT_ID"],
        client_secret: ENV["HUAWEI_CLIENT_SECRET"],
        app_id: "108212859",
        apk_path: "#{build_dir}/app-release.aab",
        is_aab: true,
        submit_for_review: false,
        phase_wise_release: false,
        changelog_path: "fastlane/metadata/android/en-US/changelogs/#{version_code}.txt",
    )
end

lane :amazon do
    upload_to_amazon_appstore(
      apk: "#{build_dir}/app-release.apk",
      client_id: ENV["AMAZON_CLIENT_ID"],
      client_secret: ENV["AMAZON_CLIENT_SECRET"],
    )
end
