#!/bin/bash

set -e # fail on errors

rm -rd screenshots

adb root
adb wait-for-device

adb shell rm -f -rR /sdcard/Pictures/screenshots
adb shell rm -f -rR /sdcard/Pictures/error_screenshots

adb shell mkdir /sdcard/testdata
adb push testdata /sdcard/

for ((n=0;n<5;n++)) # setting those is very flaky on the emulator, running them multiple times
do
 adb shell settings put global sysui_demo_allowed 1
 adb shell am broadcast -a com.android.systemui.demo -e command clock -e hhmm 1200
 adb shell am broadcast -a com.android.systemui.demo -e command notifications -e visible false
 adb shell am broadcast -a com.android.systemui.demo -e command network -e mobile hide
 adb shell am broadcast -a com.android.systemui.demo -e command network -e wifi hide
 adb shell am broadcast -a com.android.systemui.demo -e command battery -e level 100 -e plugged false
done

set +e # don't fail on errors

adb shell "screenrecord --size 1024x768 /sdcard/screen1.mp4; screenrecord --size 1024x768 /sdcard/screen2.mp4; screenrecord --size 1024x768 /sdcard/screen3.mp4; screenrecord --size 1024x768 /sdcard/screen4.mp4" &

./gradlew :app:connectedDebugAndroidTest
exit_code=$?

for ((n=0;n<5;n++))
do
  adb shell kill -2 $(adb shell pidof screenrecord)
done

mkdir app/build/screenrecording
adb pull /sdcard/screen1.mp4 app/build/screenrecording/screen1.mp4
adb pull /sdcard/screen2.mp4 app/build/screenrecording/screen2.mp4
adb pull /sdcard/screen3.mp4 app/build/screenrecording/screen3.mp4
adb pull /sdcard/screen4.mp4 app/build/screenrecording/screen4.mp4

adb pull /sdcard/Pictures/error_screenshots app/build
set -e # fail on errors
adb pull /sdcard/Pictures/screenshots

exit $exit_code
