name: Update Play Store Metadata

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      RUBY_VERSION: '3.2.2'
      CREDENTIALS_DIR: 'credentials'

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
        
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: $RUBY_VERSION

    - name: Setup Fastlane
      run: bundle install
      
    - name: Update metadata on Google Play
      run: |
        echo "$PLAY_STORE_CREDENTIALS" > $CREDENTIALS_DIR/playstore_access.json.txt
        base64 -d $CREDENTIALS_DIR/playstore_access.json.txt > $CREDENTIALS_DIR/playstore_access.json
        bundle exec fastlane google_metadata
      env:
        PLAY_STORE_CREDENTIALS: ${{ secrets.PLAY_STORE_CREDENTIALS }}
