name: Update Play Store Metadata

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    
    - name: Set up play store access
      run: |
        echo "$PLAY_STORE_CREDENTIALS" > playstore_access.json.txt
        base64 -d playstore_access.json.txt > playstore_access.json
        rm playstore_access.json.txt
      env:
        PLAY_STORE_CREDENTIALS: ${{ secrets.PLAY_STORE_CREDENTIALS }}
        
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'

    - name: Setup Fastlane
      run: bundle install
      
    - name: Update Metadata on Google Play
      run: bundle exec fastlane supply --skip_upload_changelogs
